var modules_FEN20_4IOL=
[{
	mod_name:"Basic",
	mod_id:0x4082082,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:1,
		datapoints:
		[
		{
			name:"Manual reset after overcurr.",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		],
	max_size:4,
	},
	{
		sect_name:"Diag",
		num_elems:5,
		datapoints:
		[
		{
			name:"Overcurrent supply VAUX1 Ch0",
			category:"IOL",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent supply VAUX1 Ch1",
			category:"IOL",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent supply VAUX1 Ch2",
			category:"IOL",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent supply VAUX1 Ch3",
			category:"IOL",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent output",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:8,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:12,
	},
	{
		sect_name:"Input",
		num_elems:2,
		datapoints:
		[
		{
			name:"DI input",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"Input values valid",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:8,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		],
	max_size:12,
	},
	{
		sect_name:"Output",
		num_elems:1,
		datapoints:
		[
		{
			name:"Output value",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:2,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		],
	max_size:4,
	},
	]
},
{
	mod_name:"Diagnostics",
	mod_id:0x2240000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:20,
		datapoints:
		[
		{
			name:"Overcurrent supply VAUX1 Ch0",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent supply VAUX1 Ch1",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent supply VAUX1 Ch2",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent supply VAUX1 Ch3",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent output",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:8,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Wrong or missing device",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:18,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:19,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:21,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:20,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:22,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:23,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:24,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:25,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:26,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:27,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:28,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:29,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:30,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:31,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:17,
			bitLen:1,
			bitIncremental:16,
			channelNumStart:0,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:95,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"IO-Link Events",
	mod_id:0x640000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:3,
		datapoints:
		[
		{
			name:"Port",
			category:"IO-Link event",
			chan_unit:"event",
			bitOffset:8,
			bitLen:8,
			bitIncremental:32,
			channelNumStart:1,
			channelNumEnd:16,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Qualifier",
			category:"IO-Link event",
			chan_unit:"event",
			bitOffset:0,
			bitLen:8,
			bitIncremental:32,
			channelNumStart:1,
			channelNumEnd:16,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Event code",
			category:"IO-Link event",
			chan_unit:"event",
			bitOffset:16,
			bitLen:16,
			bitIncremental:32,
			channelNumStart:1,
			channelNumEnd:16,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:528,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"IO-Link Port",
	mod_id:0x3492302,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:12,
		datapoints:
		[
		{
			name:"Operation mode",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:0,
			bitLen:4,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:7,
			defaultValue:0,
			enumValues:
				[
				0,
				"IO-Link without validation",
				1,
				"IO-Link with family compatible device",
				2,
				"IO-Link with compatible device",
				3,
				"IO-Link with identical device",
				4,
				"DI (with parameter access)",
				8,
				"DI",
				9,
				"DX",
				],
		},
		{
			name:"Data storage mode",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:4,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:4,
			defaultValue:3,
			enumValues:
				[
				0,
				"activated",
				1,
				"overwrite",
				2,
				"read in",
				3,
				"deactivated, clear",
				],
		},
		{
			name:"Cycle time",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:8,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:91,
			defaultValue:0,
			enumValues:
				[
				0,
				"automatic",
				16,
				"1.6 ms",
				24,
				"2.4 ms",
				32,
				"3.2 ms",
				40,
				"4.0 ms",
				48,
				"4.8 ms",
				56,
				"5.6 ms",
				64,
				"6.4 ms",
				66,
				"7.2 ms",
				68,
				"8.0 ms",
				70,
				"8.8 ms",
				72,
				"9.6 ms",
				74,
				"10.4 ms",
				76,
				"11.2 ms",
				78,
				"12.0 ms",
				80,
				"12.8 ms",
				84,
				"14.4 ms",
				88,
				"16.0 ms",
				92,
				"17.6 ms",
				96,
				"19.2 ms",
				100,
				"20.8 ms",
				104,
				"22.4 ms",
				108,
				"24.0 ms",
				112,
				"25.6 ms",
				116,
				"27.2 ms",
				120,
				"28.8 ms",
				124,
				"30.4 ms",
				128,
				"32.0 ms",
				129,
				"33.6 ms",
				130,
				"35.2 ms",
				131,
				"36.8 ms",
				132,
				"38.4 ms",
				133,
				"40.0 ms",
				134,
				"41.6 ms",
				135,
				"43.2 ms",
				136,
				"44.8 ms",
				137,
				"46.4 ms",
				138,
				"48.0 ms",
				139,
				"49.6 ms",
				140,
				"51.2 ms",
				141,
				"52.8 ms",
				142,
				"54.4 ms",
				143,
				"56.0 ms",
				144,
				"57.6 ms",
				145,
				"59.2 ms",
				146,
				"60.8 ms",
				147,
				"62.4 ms",
				148,
				"64.0 ms",
				149,
				"65.6 ms",
				150,
				"67.2 ms",
				151,
				"68.8 ms",
				152,
				"70.4 ms",
				153,
				"72.0 ms",
				154,
				"73.6 ms",
				155,
				"75.2 ms",
				156,
				"76.8 ms",
				157,
				"78.4 ms",
				158,
				"80.0 ms",
				159,
				"81.6 ms",
				160,
				"83.2 ms",
				161,
				"84.8 ms",
				162,
				"86.4 ms",
				163,
				"88.0 ms",
				164,
				"89.6 ms",
				165,
				"91.2 ms",
				166,
				"92.8 ms",
				167,
				"94.4 ms",
				168,
				"96.0 ms",
				169,
				"97.6 ms",
				170,
				"99.2 ms",
				171,
				"100.8 ms",
				172,
				"102.4 ms",
				173,
				"104.0 ms",
				174,
				"105.6 ms",
				175,
				"107.2 ms",
				176,
				"108.8 ms",
				177,
				"110.4 ms",
				178,
				"112.0 ms",
				179,
				"113.6 ms",
				180,
				"115.2 ms",
				181,
				"116.8 ms",
				182,
				"118.4 ms",
				183,
				"120.0 ms",
				184,
				"121.6 ms",
				185,
				"123.2 ms",
				186,
				"124.8 ms",
				187,
				"126.4 ms",
				188,
				"128.0 ms",
				189,
				"129.6 ms",
				190,
				"131.2 ms",
				191,
				"132.8 ms",
				],
		},
		{
			name:"Revision",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:16,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"automatic",
				1,
				"V1.0",
				],
		},
		{
			name:"Activate Quick Start-Up",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Device parametrization via GSD",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"inactive",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:17,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"diagnostic generated",
				1,
				"no diagnostic generated",
				],
		},
		{
			name:"Deactivate diagnostics",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:18,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:4,
			defaultValue:2,
			enumValues:
				[
				0,
				"no",
				1,
				"notifications",
				2,
				"notifications and warnings",
				3,
				"yes",
				],
		},
		{
			name:"Input data mapping",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:20,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:4,
			defaultValue:1,
			enumValues:
				[
				0,
				"direct",
				1,
				"swap 16 bit",
				2,
				"swap 32 bit",
				3,
				"swap all",
				],
		},
		{
			name:"Output data mapping",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:22,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:4,
			defaultValue:1,
			enumValues:
				[
				0,
				"direct",
				1,
				"swap 16 bit",
				2,
				"swap 32 bit",
				3,
				"swap all",
				],
		},
		{
			name:"Vendor ID",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:64,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Device ID",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:80,
			bitLen:32,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:112,
	},
	{
		sect_name:"Diag",
		num_elems:15,
		datapoints:
		[
		{
			name:"Wrong or missing device",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:8,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:9,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:10,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:11,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:12,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:13,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:14,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:15,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:16,
	},
	{
		sect_name:"Input",
		num_elems:16,
		datapoints:
		[
		{
			name:"Input data word 0",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:0,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 1",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:16,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 2",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:32,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 3",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:48,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 4",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:64,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 5",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:80,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 6",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:96,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 7",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:112,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 8",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:128,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 9",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:144,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 10",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:160,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 11",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:176,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 12",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:192,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 13",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:208,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 14",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:224,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 15",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:240,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:256,
	},
	{
		sect_name:"Output",
		num_elems:16,
		datapoints:
		[
		{
			name:"Output data word 0",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:0,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 1",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:16,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 2",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:32,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 3",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:48,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 4",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:64,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 5",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:80,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 6",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:96,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 7",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:112,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 8",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:128,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 9",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:144,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 10",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:160,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 11",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:176,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 12",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:192,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 13",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:208,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 14",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:224,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 15",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:240,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:256,
	},
	]
},
{
	mod_name:"Module status",
	mod_id:0x13080000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:5,
		datapoints:
		[
		{
			name:"I/O-ASSISTANT Force Mode active",
			category:"Module state",
			chan_unit:"",
			bitOffset:14,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage V1",
			category:"Module state",
			chan_unit:"",
			bitOffset:9,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Module diagnostics available",
			category:"Module state",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Internal error",
			category:"Module state",
			chan_unit:"",
			bitOffset:10,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"ARGEE program active",
			category:"Module state",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:15,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"VAUX control",
	mod_id:0x4002100,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:4,
		datapoints:
		[
		{
			name:"VAUX1 Pin3 (Ch0)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:0,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		{
			name:"VAUX1 Pin5 (Ch1)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:8,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		{
			name:"VAUX1 Pin7 (Ch2)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:16,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		{
			name:"VAUX1 Pin9 (Ch3)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:24,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		],
	max_size:26,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Output",
		num_elems:4,
		datapoints:
		[
		{
			name:"VAUX1 Pin3 (Ch0)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"VAUX1 Pin5 (Ch1)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"VAUX1 Pin7 (Ch2)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"VAUX1 Pin9 (Ch3)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		],
	max_size:4,
	},
	]
},
];
