var modules_TBEN_LX_8IOLA=
[{
	mod_name:"Module status",
	mod_id:0x13080000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:5,
		datapoints:
		[
		{
			name:"I/O-ASSISTANT Force Mode active",
			category:"Module state",
			chan_unit:"",
			bitOffset:14,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage V1",
			category:"Module state",
			chan_unit:"",
			bitOffset:9,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Module diagnostics available",
			category:"Module state",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Internal error",
			category:"Module state",
			chan_unit:"",
			bitOffset:10,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"ARGEE program active",
			category:"Module state",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:15,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"IO-Link Events",
	mod_id:0x640000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:3,
		datapoints:
		[
		{
			name:"Port",
			category:"IO-Link event",
			chan_unit:"event",
			bitOffset:8,
			bitLen:8,
			bitIncremental:32,
			channelNumStart:1,
			channelNumEnd:16,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Qualifier",
			category:"IO-Link event",
			chan_unit:"event",
			bitOffset:0,
			bitLen:8,
			bitIncremental:32,
			channelNumStart:1,
			channelNumEnd:16,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Event code",
			category:"IO-Link event",
			chan_unit:"event",
			bitOffset:16,
			bitLen:16,
			bitIncremental:32,
			channelNumStart:1,
			channelNumEnd:16,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:528,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"IO-Link Port",
	mod_id:0x3492302,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:12,
		datapoints:
		[
		{
			name:"Operation mode",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:0,
			bitLen:4,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:7,
			defaultValue:0,
			enumValues:
				[
				0,
				"IO-Link without validation",
				1,
				"IO-Link with family compatible device",
				2,
				"IO-Link with compatible device",
				3,
				"IO-Link with identical device",
				4,
				"DI (with parameter access)",
				8,
				"DI",
				9,
				"DX",
				],
		},
		{
			name:"Data storage mode",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:4,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:4,
			defaultValue:3,
			enumValues:
				[
				0,
				"activated",
				1,
				"overwrite",
				2,
				"read in",
				3,
				"deactivated, clear",
				],
		},
		{
			name:"Cycle time",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:8,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:92,
			defaultValue:0,
			enumValues:
				[
				0,
				"automatic",
				16,
				"1.6 ms",
				24,
				"2.4 ms",
				32,
				"3.2 ms",
				40,
				"4.0 ms",
				48,
				"4.8 ms",
				56,
				"5.6 ms",
				64,
				"6.4 ms",
				66,
				"7.2 ms",
				68,
				"8.0 ms",
				70,
				"8.8 ms",
				72,
				"9.6 ms",
				74,
				"10.4 ms",
				76,
				"11.2 ms",
				78,
				"12.0 ms",
				80,
				"12.8 ms",
				84,
				"14.4 ms",
				88,
				"16.0 ms",
				92,
				"17.6 ms",
				96,
				"19.2 ms",
				100,
				"20.8 ms",
				104,
				"22.4 ms",
				108,
				"24.0 ms",
				112,
				"25.6 ms",
				116,
				"27.2 ms",
				120,
				"28.8 ms",
				124,
				"30.4 ms",
				128,
				"32.0 ms",
				129,
				"33.6 ms",
				130,
				"35.2 ms",
				131,
				"36.8 ms",
				132,
				"38.4 ms",
				133,
				"40.0 ms",
				134,
				"41.6 ms",
				135,
				"43.2 ms",
				136,
				"44.8 ms",
				137,
				"46.4 ms",
				138,
				"48.0 ms",
				139,
				"49.6 ms",
				140,
				"51.2 ms",
				141,
				"52.8 ms",
				142,
				"54.4 ms",
				143,
				"56.0 ms",
				144,
				"57.6 ms",
				145,
				"59.2 ms",
				146,
				"60.8 ms",
				147,
				"62.4 ms",
				148,
				"64.0 ms",
				149,
				"65.6 ms",
				150,
				"67.2 ms",
				151,
				"68.8 ms",
				152,
				"70.4 ms",
				153,
				"72.0 ms",
				154,
				"73.6 ms",
				155,
				"75.2 ms",
				156,
				"76.8 ms",
				157,
				"78.4 ms",
				158,
				"80.0 ms",
				159,
				"81.6 ms",
				160,
				"83.2 ms",
				161,
				"84.8 ms",
				162,
				"86.4 ms",
				163,
				"88.0 ms",
				164,
				"89.6 ms",
				165,
				"91.2 ms",
				166,
				"92.8 ms",
				167,
				"94.4 ms",
				168,
				"96.0 ms",
				169,
				"97.6 ms",
				170,
				"99.2 ms",
				171,
				"100.8 ms",
				172,
				"102.4 ms",
				173,
				"104.0 ms",
				174,
				"105.6 ms",
				175,
				"107.2 ms",
				176,
				"108.8 ms",
				177,
				"110.4 ms",
				178,
				"112.0 ms",
				179,
				"113.6 ms",
				180,
				"115.2 ms",
				181,
				"116.8 ms",
				182,
				"118.4 ms",
				183,
				"120.0 ms",
				184,
				"121.6 ms",
				185,
				"123.2 ms",
				186,
				"124.8 ms",
				187,
				"126.4 ms",
				188,
				"128.0 ms",
				189,
				"129.6 ms",
				190,
				"131.2 ms",
				191,
				"132.8 ms",
				255,
				"automatic, compatible",
				],
		},
		{
			name:"Revision",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:16,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"automatic",
				1,
				"V1.0",
				],
		},
		{
			name:"Activate Quick Start-Up",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Device parametrization via GSD",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"inactive",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:17,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"diagnostic generated",
				1,
				"no diagnostic generated",
				],
		},
		{
			name:"Deactivate diagnostics",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:18,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:4,
			defaultValue:2,
			enumValues:
				[
				0,
				"no",
				1,
				"notifications",
				2,
				"notifications and warnings",
				3,
				"yes",
				],
		},
		{
			name:"Input data mapping",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:20,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:4,
			defaultValue:1,
			enumValues:
				[
				0,
				"direct",
				1,
				"swap 16 bit",
				2,
				"swap 32 bit",
				3,
				"swap all",
				],
		},
		{
			name:"Output data mapping",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:22,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:4,
			defaultValue:1,
			enumValues:
				[
				0,
				"direct",
				1,
				"swap 16 bit",
				2,
				"swap 32 bit",
				3,
				"swap all",
				],
		},
		{
			name:"Vendor ID",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:64,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Device ID",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:80,
			bitLen:32,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:112,
	},
	{
		sect_name:"Diag",
		num_elems:15,
		datapoints:
		[
		{
			name:"Wrong or missing device",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:8,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:9,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:10,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:11,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:12,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:13,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:14,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:15,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:16,
	},
	{
		sect_name:"Input",
		num_elems:16,
		datapoints:
		[
		{
			name:"Input data word 0",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:0,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 1",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:16,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 2",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:32,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 3",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:48,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 4",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:64,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 5",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:80,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 6",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:96,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 7",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:112,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 8",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:128,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 9",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:144,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 10",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:160,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 11",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:176,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 12",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:192,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 13",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:208,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 14",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:224,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Input data word 15",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:240,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:256,
	},
	{
		sect_name:"Output",
		num_elems:16,
		datapoints:
		[
		{
			name:"Output data word 0",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:0,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 1",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:16,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 2",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:32,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 3",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:48,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 4",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:64,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 5",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:80,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 6",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:96,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 7",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:112,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 8",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:128,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 9",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:144,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 10",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:160,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 11",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:176,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 12",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:192,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 13",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:208,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 14",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:224,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Output data word 15",
			category:"IO-Link port",
			chan_unit:"",
			bitOffset:240,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:256,
	},
	]
},
{
	mod_name:"Basic",
	mod_id:0x4102104,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:9,
		datapoints:
		[
		{
			name:"Manual reset after overcurr.",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:0,
			channelNumEnd:15,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Activate output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:17,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:1,
			channelNumEnd:1,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Activate output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:19,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:3,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Activate output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:21,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:5,
			channelNumEnd:5,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Activate output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:23,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:7,
			channelNumEnd:7,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Activate output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:25,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:9,
			channelNumEnd:9,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Activate output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:27,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:11,
			channelNumEnd:11,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Activate output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:29,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:13,
			channelNumEnd:13,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Activate output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:31,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:15,
			channelNumEnd:15,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		],
	max_size:32,
	},
	{
		sect_name:"Diag",
		num_elems:9,
		datapoints:
		[
		{
			name:"Overcurrent VAUX1 Pin1 C0 (Ch0/1)",
			category:"DXP",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C1 (Ch2/3)",
			category:"DXP",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C2 (Ch4/5)",
			category:"DXP",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C3 (Ch6/7)",
			category:"DXP",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C4 (Ch8/9)",
			category:"DXP",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C5 (Ch10/11)",
			category:"DXP",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C6 (Ch12/13)",
			category:"DXP",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C7 (Ch14/15)",
			category:"DXP",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:16,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:0,
			channelNumEnd:15,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:32,
	},
	{
		sect_name:"Input",
		num_elems:24,
		datapoints:
		[
		{
			name:"DI input",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DI input",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DI input",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DI input",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DI input",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:8,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DI input",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:10,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DI input",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:12,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DI input",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:14,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"Input values valid",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:16,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Input values valid",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:18,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Input values valid",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:20,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Input values valid",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:22,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Input values valid",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:24,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Input values valid",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:26,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Input values valid",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:28,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Input values valid",
			category:"IOL",
			chan_unit:"Channel",
			bitOffset:30,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"DXP input value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:1,
			channelNumEnd:1,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DXP input value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:3,
			channelNumEnd:3,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DXP input value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:5,
			channelNumEnd:5,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DXP input value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:7,
			channelNumEnd:7,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DXP input value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:9,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:9,
			channelNumEnd:9,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DXP input value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:11,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:11,
			channelNumEnd:11,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DXP input value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:13,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:13,
			channelNumEnd:13,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"DXP input value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:15,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:15,
			channelNumEnd:15,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		],
	max_size:31,
	},
	{
		sect_name:"Output",
		num_elems:1,
		datapoints:
		[
		{
			name:"Output value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:0,
			channelNumEnd:15,
			dataType:2,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		],
	max_size:16,
	},
	]
},
{
	mod_name:"VAUX control",
	mod_id:0x2002300,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:8,
		datapoints:
		[
		{
			name:"VAUX1 Pin1 C0 (Ch0/1)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:0,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		{
			name:"VAUX1 Pin1 C1 (Ch2/3)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:8,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		{
			name:"VAUX1 Pin1 C2 (Ch4/5)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:16,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		{
			name:"VAUX1 Pin1 C3 (Ch6/7)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:24,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		{
			name:"VAUX1 Pin1 C4 (Ch8/9)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:32,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		{
			name:"VAUX1 Pin1 C5 (Ch10/11)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:40,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		{
			name:"VAUX1 Pin1 C6 (Ch12/13)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:48,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		{
			name:"VAUX1 Pin1 C7 (Ch14/15)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:56,
			bitLen:2,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:3,
			defaultValue:0,
			enumValues:
				[
				0,
				"24 VDC",
				1,
				"switchable",
				2,
				"off",
				],
		},
		],
	max_size:58,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Output",
		num_elems:8,
		datapoints:
		[
		{
			name:"VAUX1 Pin1 C0 (Ch0/1)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"VAUX1 Pin1 C1 (Ch2/3)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"VAUX1 Pin1 C2 (Ch4/5)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"VAUX1 Pin1 C3 (Ch6/7)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"VAUX1 Pin1 C4 (Ch8/9)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"VAUX1 Pin1 C5 (Ch10/11)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"VAUX1 Pin1 C6 (Ch12/13)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		{
			name:"VAUX1 Pin1 C7 (Ch14/15)",
			category:"VAUX control",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		],
	max_size:8,
	},
	]
},
{
	mod_name:"Diagnostics",
	mod_id:0x2380000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:129,
		datapoints:
		[
		{
			name:"Overcurrent VAUX1 Pin1 C0 (Ch0/1)",
			category:"Group diagnosis",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C1 (Ch2/3)",
			category:"Group diagnosis",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C2 (Ch4/5)",
			category:"Group diagnosis",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C3 (Ch6/7)",
			category:"Group diagnosis",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C4 (Ch8/9)",
			category:"Group diagnosis",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C5 (Ch10/11)",
			category:"Group diagnosis",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C6 (Ch12/13)",
			category:"Group diagnosis",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX1 Pin1 C7 (Ch14/15)",
			category:"Group diagnosis",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent output",
			category:"DXP channel",
			chan_unit:"Channel",
			bitOffset:16,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:0,
			channelNumEnd:15,
			dataType:2,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Wrong or missing device",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:34,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Wrong or missing device",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:50,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Wrong or missing device",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:66,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Wrong or missing device",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:82,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Wrong or missing device",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:98,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Wrong or missing device",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:114,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Wrong or missing device",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:130,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Wrong or missing device",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:146,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:35,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:51,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:67,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:83,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:99,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:115,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:131,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Data storage error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:147,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:37,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:53,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:69,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:85,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:101,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:117,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:133,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Process input data invalid",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:149,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:36,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:52,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:68,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:84,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:100,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:116,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:132,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Hardware error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:148,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:38,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:54,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:70,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:86,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:102,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:118,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:134,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Maintenance events",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:150,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:39,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:55,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:71,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:87,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:103,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:119,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:135,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Out of spec. error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:151,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:40,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:56,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:72,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:88,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:104,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:120,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:136,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:152,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:41,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:57,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:73,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:89,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:105,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:121,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:137,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overtemperature",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:153,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:42,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:58,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:74,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:90,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:106,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:122,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:138,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Lower limit value underrun",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:154,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:43,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:59,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:75,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:91,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:107,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:123,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:139,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Upper limit value exceeded",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:155,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:44,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:60,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:76,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:92,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:108,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:124,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:140,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:156,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:45,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:61,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:77,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:93,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:109,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:125,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:141,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overvoltage",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:157,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:46,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:62,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:78,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:94,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:110,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:126,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:142,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overload",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:158,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:47,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:63,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:79,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:95,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:111,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:127,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:143,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Common error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:159,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:33,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:49,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:65,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:81,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:97,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:113,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:129,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Port parameterization error",
			category:"IO-Link channel",
			chan_unit:"Channel",
			bitOffset:145,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:160,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"IO-Link Identification",
	mod_id:0x2580000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:2,
		datapoints:
		[
		{
			name:"Vendor ID",
			category:"IO-Link identification",
			chan_unit:"p",
			bitOffset:0,
			bitLen:16,
			bitIncremental:48,
			channelNumStart:1,
			channelNumEnd:8,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Device ID",
			category:"IO-Link identification",
			chan_unit:"p",
			bitOffset:16,
			bitLen:32,
			bitIncremental:48,
			channelNumStart:1,
			channelNumEnd:8,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:400,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
];
