var modules_TBEN_S2_2RFID=
[{
	mod_name:"DXP",
	mod_id:0x82082,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:2,
		datapoints:
		[
		{
			name:"Manual reset after overcurr.",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:4,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:4,
			channelNumEnd:7,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Activate output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:12,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:4,
			channelNumEnd:7,
			dataType:1,
			enumLen:2,
			defaultValue:1,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		],
	max_size:16,
	},
	{
		sect_name:"Diag",
		num_elems:3,
		datapoints:
		[
		{
			name:"Overcurrent VAUX2 Ch4/5",
			category:"DXP",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX2 Ch6/7",
			category:"DXP",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:12,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:4,
			channelNumEnd:7,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:16,
	},
	{
		sect_name:"Input",
		num_elems:1,
		datapoints:
		[
		{
			name:"Input value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:4,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:4,
			channelNumEnd:7,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		],
	max_size:8,
	},
	{
		sect_name:"Output",
		num_elems:1,
		datapoints:
		[
		{
			name:"Output value",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:4,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:4,
			channelNumEnd:7,
			dataType:2,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"off",
				1,
				"on",
				],
		},
		],
	max_size:8,
	},
	]
},
{
	mod_name:"DXP diagnostics",
	mod_id:0x3080000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:3,
		datapoints:
		[
		{
			name:"Overcurrent VAUX2 Ch4/5",
			category:"DXP",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent VAUX2 Ch6/7",
			category:"DXP",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Overcurrent output",
			category:"DXP",
			chan_unit:"Channel",
			bitOffset:12,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:4,
			channelNumEnd:7,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:16,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"Module status",
	mod_id:0x80000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:5,
		datapoints:
		[
		{
			name:"I/O-ASSISTANT Force Mode active",
			category:"Module state",
			chan_unit:"",
			bitOffset:14,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage V1",
			category:"Module state",
			chan_unit:"",
			bitOffset:9,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Undervoltage V2",
			category:"Module state",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Module diagnostics available",
			category:"Module state",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Internal error",
			category:"Module state",
			chan_unit:"",
			bitOffset:10,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:15,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"Ext. DXP functions",
	mod_id:0x80,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:3,
		datapoints:
		[
		{
			name:"extended digital mode",
			category:"DXP extended",
			chan_unit:"",
			bitOffset:0,
			bitLen:7,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"deactivated",
				1,
				"digital filter and impulse stretch",
				],
		},
		{
			name:"input filter",
			category:"DXP extended",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"0.2 ms",
				1,
				"3 ms",
				],
		},
		{
			name:"impulse stretch (*10ms)",
			category:"DXP extended",
			chan_unit:"",
			bitOffset:8,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:16,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"RFID diagnostics",
	mod_id:0x680000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:16,
		datapoints:
		[
		{
			name:"Overcurrent supply VAUX1",
			category:"CH0 diagnosis",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"CH0 diagnosis",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Configuration via DTM active",
			category:"CH0 diagnosis",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Buffer full",
			category:"CH0 diagnosis",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"HF Read/write head address  detuned",
			category:"CH0 head",
			chan_unit:"head",
			bitOffset:36,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Parameter not supported by read/write head address",
			category:"CH0 head",
			chan_unit:"head",
			bitOffset:37,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Read/write head address  reports error",
			category:"CH0 head",
			chan_unit:"head",
			bitOffset:38,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Expected read/write head address  not connected",
			category:"CH0 head",
			chan_unit:"head",
			bitOffset:39,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Overcurrent supply VAUX1",
			category:"CH1 diagnosis",
			chan_unit:"",
			bitOffset:295,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:1,
			channelNumEnd:1,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"CH1 diagnosis",
			chan_unit:"",
			bitOffset:294,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:1,
			channelNumEnd:1,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Configuration via DTM active",
			category:"CH1 diagnosis",
			chan_unit:"",
			bitOffset:293,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:1,
			channelNumEnd:1,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Buffer full",
			category:"CH1 diagnosis",
			chan_unit:"",
			bitOffset:292,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:1,
			channelNumEnd:1,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"HF Read/write head address  detuned",
			category:"CH1 head",
			chan_unit:"head",
			bitOffset:324,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Parameter not supported by read/write head address",
			category:"CH1 head",
			chan_unit:"head",
			bitOffset:325,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Read/write head address  reports error",
			category:"CH1 head",
			chan_unit:"head",
			bitOffset:326,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Expected read/write head address  not connected",
			category:"CH1 head",
			chan_unit:"head",
			bitOffset:327,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		],
	max_size:583,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"RFID read data",
	mod_id:0x840080,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:1,
		datapoints:
		[
		{
			name:"Length of read data",
			category:"RFID read data",
			chan_unit:"",
			bitOffset:0,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:128,
			enumValues:
				[
				],
		},
		],
	max_size:16,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:1,
		datapoints:
		[
		{
			name:"Input buffer",
			category:"Byte",
			chan_unit:"byte",
			bitOffset:0,
			bitLen:8,
			bitIncremental:8,
			channelNumStart:0,
			channelNumEnd:127,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:1024,
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	]
},
{
	mod_name:"RFID write data",
	mod_id:0x21080,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:1,
		datapoints:
		[
		{
			name:"Length of write data",
			category:"RFID write data",
			chan_unit:"",
			bitOffset:0,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:128,
			enumValues:
				[
				],
		},
		],
	max_size:16,
	},
	{
		sect_name:"Diag",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Input",
		num_elems:0,
		datapoints:
		[
		],
	max_size:0,
	},
	{
		sect_name:"Output",
		num_elems:1,
		datapoints:
		[
		{
			name:"Output buffer",
			category:"Byte",
			chan_unit:"byte",
			bitOffset:0,
			bitLen:8,
			bitIncremental:8,
			channelNumStart:0,
			channelNumEnd:127,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:1024,
	},
	]
},
{
	mod_name:"RFID control/status",
	mod_id:0x410493,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:15,
		datapoints:
		[
		{
			name:"Operation mode",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:0,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:6,
			defaultValue:1,
			enumValues:
				[
				0,
				"deactivated",
				1,
				"HF compact",
				2,
				"HF extended",
				3,
				"HF bus mode",
				4,
				"UHF compact",
				5,
				"UHF extended",
				],
		},
		{
			name:"HF: Select Tag type",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:8,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:19,
			defaultValue:0,
			enumValues:
				[
				0,
				"automatic tag detection HF (1 to 4)",
				1,
				"1: Philips I-CODE SLI SL2",
				2,
				"2: Fujitsu MB89R118",
				3,
				"3: TI Tag-it HF-I Plus",
				4,
				"4: Infineon SRF55V02P",
				5,
				"5: Philips I-CODE SLI S",
				6,
				"6: Fujitsu MB89R119",
				7,
				"7: TI Tag-it HF-I",
				8,
				"8: Infineon SRF55V10P",
				11,
				"11: NXP I-CODE SLI L",
				12,
				"12: Fujitsu MB89R112",
				13,
				"13: EM4233SLIC",
				14,
				"14: reserved",
				15,
				"15: reserved",
				16,
				"16: reserved",
				17,
				"17: reserved",
				18,
				"18: reserved",
				19,
				"19: reserved",
				20,
				"20: reserved",
				],
		},
		{
			name:"HF: Bypass time (*1ms)",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:16,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:200,
			enumValues:
				[
				],
		},
		{
			name:"HF: Multitag",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:36,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"HF: Heart beat read/write head",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:37,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Termination active",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:38,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"yes",
				1,
				"no",
				],
		},
		{
			name:"HF: Autotuning read/write head",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:39,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Deactivate HF detuned diagnostic",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:40,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Deactivate diagnostics",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:47,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"HF: Idle mode",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:48,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:5,
			defaultValue:0,
			enumValues:
				[
				0,
				"UID",
				1,
				"8 bytes user memory",
				2,
				"UID + 8 bytes user memory",
				3,
				"UID + 64 bytes user memory",
				4,
				"deactivated",
				],
		},
		{
			name:"Command retries at failure",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:64,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:2,
			enumValues:
				[
				],
		},
		{
			name:"HF: Command in continuous mode",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:72,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:4,
			defaultValue:1,
			enumValues:
				[
				1,
				"Inventory",
				2,
				"Read",
				3,
				"Tag info",
				4,
				"Write",
				],
		},
		{
			name:"HF: Length in continuous mode",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:80,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:8,
			enumValues:
				[
				],
		},
		{
			name:"HF: Address in continuous mode",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:96,
			bitLen:32,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Activate read-write-head",
			category:"Head",
			chan_unit:"head",
			bitOffset:224,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		],
	max_size:256,
	},
	{
		sect_name:"Diag",
		num_elems:8,
		datapoints:
		[
		{
			name:"Overcurrent supply VAUX1",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameterization error",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Configuration via DTM active",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Buffer full",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"HF Read/write head address  detuned",
			category:"Head",
			chan_unit:"head",
			bitOffset:36,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Parameter not supported by read/write head address",
			category:"Head",
			chan_unit:"head",
			bitOffset:37,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Read/write head address  reports error",
			category:"Head",
			chan_unit:"head",
			bitOffset:38,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		{
			name:"Expected read/write head address  not connected",
			category:"Head",
			chan_unit:"head",
			bitOffset:39,
			bitLen:1,
			bitIncremental:8,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"-",
				1,
				"active",
				],
		},
		],
	max_size:295,
	},
	{
		sect_name:"Input",
		num_elems:14,
		datapoints:
		[
		{
			name:"Response code",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:0,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:65,
			defaultValue:0,
			enumValues:
				[
				0,
				"0x0000 Idle",
				1,
				"0x0001 Inventory",
				2,
				"0x0002 Read",
				4,
				"0x0004 Write",
				8,
				"0x0008 Write and Verify",
				16,
				"0x0010 Continuous Mode",
				17,
				"0x0011 Get data from buffer (Continuous Mode)",
				32,
				"0x0020 UHF Continuous Presence Sensing Mode",
				64,
				"0x0040 HF Read/write head off",
				65,
				"0x0041 Read/write head identification",
				80,
				"0x0050 Tag info",
				96,
				"0x0060 Direct read/write head command",
				128,
				"0x0080 Tune HF Read/write head",
				256,
				"0x0100 Set read/write head password",
				257,
				"0x0101 Reset read/write head password",
				258,
				"0x0102 Set tag password",
				259,
				"0x0103 Set tag protection",
				260,
				"0x0104 Get HF tag protection status",
				261,
				"0x0105 Set perma lock",
				512,
				"0x0200 Kill UHF tag",
				4096,
				"0x1000 Restore settings UHF read/write head",
				4097,
				"0x1001 Backup settings UHF read/write head",
				16385,
				"0x4001 Error - Inventory",
				16386,
				"0x4002 Error - Read",
				16388,
				"0x4004 Error - Write",
				16392,
				"0x4008 Error - Write and Verify",
				16400,
				"0x4010 Error - Continuous Mode",
				16401,
				"0x4011 Error - Get data from buffer (Continuous Mode)",
				16416,
				"0x4020 Error - UHF Continuous Presence Sensing Mode",
				16448,
				"0x4040 Error - HF Read/write head off",
				16449,
				"0x4041 Error - Read/write head identification",
				16464,
				"0x4050 Error - Tag info",
				16480,
				"0x4060 Error - Direct read/write head command",
				16512,
				"0x4080 Error - Tune HF Read/write head",
				16640,
				"0x4100 Error - Set read/write head password",
				16641,
				"0x4101 Error - Reset read/write head password",
				16642,
				"0x4102 Error - Set tag password",
				16643,
				"0x4103 Error - Set tag protection",
				16644,
				"0x4104 Error - Get HF tag protection status",
				16645,
				"0x4105 Error - Set perma lock",
				16896,
				"0x4200 Error - Kill UHF tag",
				20480,
				"0x5000 Error - Restore settings UHF read/write head",
				20481,
				"0x5001 Error - Backup settings UHF read/write head",
				32768,
				"0x8000 Busy - Reset",
				32769,
				"0x8001 Busy - Inventory",
				32770,
				"0x8002 Busy - Read",
				32772,
				"0x8004 Busy - Write",
				32776,
				"0x8008 Busy - Write and Verify",
				32784,
				"0x8010 Busy - Continuous Mode",
				32785,
				"0x8011 Busy - Get data from buffer (Continuous Mode)",
				32800,
				"0x8020 Busy - UHF Continuous Presence Sensing Mode",
				32832,
				"0x8040 Busy - HF Read/write head off",
				32833,
				"0x8041 Busy - Read/write head identification",
				32848,
				"0x8050 Busy - Tag info",
				32864,
				"0x8060 Busy - Direct read/write head command",
				32896,
				"0x8080 Busy - Tune HF Read/write head",
				33024,
				"0x8100 Busy - Set read/write head password",
				33025,
				"0x8101 Busy - Reset read/write head password",
				33026,
				"0x8102 Busy - Set tag password",
				33027,
				"0x8103 Busy - Set tag protection",
				33028,
				"0x8104 Busy - Get HF tag protection status",
				33029,
				"0x8105 Busy - Set perma lock",
				33280,
				"0x8200 Busy - Kill UHF tag",
				36864,
				"0x9000 Busy - Restore settings UHF read/write head",
				36865,
				"0x9001 Busy - Backup settings UHF read/write head",
				],
		},
		{
			name:"Tag present (address )",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:32,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Loop counter",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:16,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"HF Read/write head address  detuned",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:36,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Parameter not supported by read/write head address",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:37,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Read/write head address  reports error",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:38,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Expected read/write head address  not connected",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:39,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		{
			name:"Length",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:48,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Error code",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:64,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Tag counter",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:80,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Data (Bytes) available",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:96,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Read fragment No.",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:112,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Write fragment No.",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:120,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Tag present at R/W-head",
			category:"Head",
			chan_unit:"head",
			bitOffset:160,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:32,
			dataType:1,
			enumLen:2,
			defaultValue:0,
			enumValues:
				[
				0,
				"no",
				1,
				"yes",
				],
		},
		],
	max_size:192,
	},
	{
		sect_name:"Output",
		num_elems:10,
		datapoints:
		[
		{
			name:"Command code",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:0,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:23,
			defaultValue:0,
			enumValues:
				[
				0,
				"0x0000 Idle",
				1,
				"0x0001 Inventory",
				2,
				"0x0002 Read",
				4,
				"0x0004 Write",
				8,
				"0x0008 Write and Verify",
				16,
				"0x0010 Continuous Mode",
				17,
				"0x0011 Get data from buffer (Continuous Mode)",
				32,
				"0x0020 UHF Continuous Presence Sensing Mode",
				64,
				"0x0040 HF Read/write head off",
				65,
				"0x0041 Read/write head identification",
				80,
				"0x0050 Tag info",
				96,
				"0x0060 Direct read/write head command",
				128,
				"0x0080 Tune HF Read/write head",
				256,
				"0x0100 Set read/write head password",
				257,
				"0x0101 Reset read/write head password",
				258,
				"0x0102 Set tag password",
				259,
				"0x0103 Set tag protection",
				260,
				"0x0104 Get HF tag protection status",
				261,
				"0x0105 Set perma lock",
				512,
				"0x0200 Kill UHF tag",
				4096,
				"0x1000 Restore settings UHF read/write head",
				4097,
				"0x1001 Backup settings UHF read/write head",
				32768,
				"0x8000 Reset",
				],
		},
		{
			name:"Loop counter",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:16,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"UHF: Memory area",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:24,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:1,
			enumLen:6,
			defaultValue:0,
			enumValues:
				[
				0,
				"Kill password",
				1,
				"EPC",
				2,
				"TID",
				3,
				"User memory",
				4,
				"Access password",
				5,
				"PC (EPC length)",
				],
		},
		{
			name:"Start address for read access",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:32,
			bitLen:32,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Length",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:64,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Length of UID/EPC",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:80,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Read/write head address",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:160,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Command timeout",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:96,
			bitLen:16,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Read fragment No.",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:112,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		{
			name:"Write fragment No.",
			category:"RFID Module",
			chan_unit:"",
			bitOffset:120,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
			dataType:0,
			enumLen:0,
			defaultValue:0,
			enumValues:
				[
				],
		},
		],
	max_size:168,
	},
	]
},
];
