var modules_TBEN=
[{
	mod_name:"16DIP",
	mod_id:0x814C5000,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:17,
		datapoints:
		[
		{
			name:"Invert digital input",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:16,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:40,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:1,
			channelNumEnd:1,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:48,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:56,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:3,
			channelNumEnd:3,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:64,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:72,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:5,
			channelNumEnd:5,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:80,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:88,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:7,
			channelNumEnd:7,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:96,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:104,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:9,
			channelNumEnd:9,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:112,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:120,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:11,
			channelNumEnd:11,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:128,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:136,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:13,
			channelNumEnd:13,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:144,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:152,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:15,
			channelNumEnd:15,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:160,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:16,
			channelNumEnd:16,
		},
		]
	},
	{
		sect_name:"Diag",
		num_elems:8,
		datapoints:
		[
		{
			name:"Overcurrent VAUX1 CH1/2",
			category:"Global",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH3/4",
			category:"Global",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH5/6",
			category:"Global",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH7/8",
			category:"Global",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH9/10",
			category:"Global",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH11/12",
			category:"Global",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH13/14",
			category:"Global",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH15/16",
			category:"Global",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		]
	},
	{
		sect_name:"Input",
		num_elems:1,
		datapoints:
		[
		{
			name:"Input value",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		]
	},
	{
		sect_name:"Output",
		num_elems:0,
		datapoints:
		[
		]
	},
	]
},
{
	mod_name:"16DOP",
	mod_id:0x81670500,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:1,
		datapoints:
		[
		{
			name:"Manual output reset after overcurrent",
			category:"Digital Out",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		]
	},
	{
		sect_name:"Diag",
		num_elems:9,
		datapoints:
		[
		{
			name:"Overcurrent VAUX2 CH1/2",
			category:"Global",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 CH3/4",
			category:"Global",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 CH5/6",
			category:"Global",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 CH7/8",
			category:"Global",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 CH9/10",
			category:"Global",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 CH11/12",
			category:"Global",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 CH13/14",
			category:"Global",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 CH15/16",
			category:"Global",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Output signal overcurrent",
			category:"Digital Out",
			chan_unit:"Channel",
			bitOffset:8,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		]
	},
	{
		sect_name:"Input",
		num_elems:0,
		datapoints:
		[
		]
	},
	{
		sect_name:"Output",
		num_elems:1,
		datapoints:
		[
		{
			name:"Output value",
			category:"Digital Out",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		]
	},
	]
},
{
	mod_name:"16DXP",
	mod_id:0x816D5500,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:19,
		datapoints:
		[
		{
			name:"Invert digital input",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:16,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		{
			name:"Manual output reset after overcurrent",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:32,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		{
			name:"Output Enable",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:48,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:72,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:1,
			channelNumEnd:1,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:80,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:88,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:3,
			channelNumEnd:3,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:96,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:104,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:5,
			channelNumEnd:5,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:112,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:120,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:7,
			channelNumEnd:7,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:128,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:136,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:9,
			channelNumEnd:9,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:144,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:10,
			channelNumEnd:10,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:152,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:11,
			channelNumEnd:11,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:160,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:12,
			channelNumEnd:12,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:168,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:13,
			channelNumEnd:13,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:176,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:14,
			channelNumEnd:14,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:184,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:15,
			channelNumEnd:15,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:192,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:16,
			channelNumEnd:16,
		},
		]
	},
	{
		sect_name:"Diag",
		num_elems:9,
		datapoints:
		[
		{
			name:"Overcurrent VAUX1 CH1/2",
			category:"Global",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH3/4",
			category:"Global",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH5/6",
			category:"Global",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH7/8",
			category:"Global",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX1 CH9/10",
			category:"Global",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 CH11/12",
			category:"Global",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 CH13/14",
			category:"Global",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 CH15/16",
			category:"Global",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Output signal overcurrent",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:8,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		]
	},
	{
		sect_name:"Input",
		num_elems:1,
		datapoints:
		[
		{
			name:"Input value",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		]
	},
	{
		sect_name:"Output",
		num_elems:1,
		datapoints:
		[
		{
			name:"Output value",
			category:"Digital In/Out",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:16,
		},
		]
	},
	]
},
{
	mod_name:"8DIP-8DOP",
	mod_id:0x615B4400,
	sections:
	[
	{
		sect_name:"Param",
		num_elems:10,
		datapoints:
		[
		{
			name:"Invert digital input",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:8,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:40,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:1,
			channelNumEnd:1,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:48,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:2,
			channelNumEnd:2,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:56,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:3,
			channelNumEnd:3,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:64,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:4,
			channelNumEnd:4,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:72,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:5,
			channelNumEnd:5,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:80,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:6,
			channelNumEnd:6,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:88,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:7,
			channelNumEnd:7,
		},
		{
			name:"Pulse Stretching",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:96,
			bitLen:8,
			bitIncremental:0,
			channelNumStart:8,
			channelNumEnd:8,
		},
		{
			name:"Manual output reset after overcurrent",
			category:"Digital Out",
			chan_unit:"Channel",
			bitOffset:8,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:8,
		},
		]
	},
	{
		sect_name:"Diag",
		num_elems:9,
		datapoints:
		[
		{
			name:"Overcurrent VAUX1 Digital In CH1/2",
			category:"Global",
			chan_unit:"",
			bitOffset:0,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX2 Digital In CH3/4",
			category:"Global",
			chan_unit:"",
			bitOffset:1,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX3 Digital In CH5/6",
			category:"Global",
			chan_unit:"",
			bitOffset:2,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX4 Digital In CH7/8",
			category:"Global",
			chan_unit:"",
			bitOffset:3,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX5 Digital Out CH1/2",
			category:"Global",
			chan_unit:"",
			bitOffset:4,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX6 Digital Out CH3/4",
			category:"Global",
			chan_unit:"",
			bitOffset:5,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX7 Digital Out CH5/6",
			category:"Global",
			chan_unit:"",
			bitOffset:6,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Overcurrent VAUX8 Digital Out CH7/8",
			category:"Global",
			chan_unit:"",
			bitOffset:7,
			bitLen:1,
			bitIncremental:0,
			channelNumStart:0,
			channelNumEnd:0,
		},
		{
			name:"Output signal overcurrent",
			category:"Digital Out",
			chan_unit:"Channel",
			bitOffset:8,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:8,
		},
		]
	},
	{
		sect_name:"Input",
		num_elems:1,
		datapoints:
		[
		{
			name:"Input value",
			category:"Digital In",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:8,
		},
		]
	},
	{
		sect_name:"Output",
		num_elems:1,
		datapoints:
		[
		{
			name:"Output value",
			category:"Digital Out",
			chan_unit:"Channel",
			bitOffset:0,
			bitLen:1,
			bitIncremental:1,
			channelNumStart:1,
			channelNumEnd:8,
		},
		]
	},
	]
},
];
